//
//  TorrentField.swift
//  
//
//  Created by 👽 on 9/15/20.
//

import Foundation

enum TorrentField: String, Encodable {
    case activityDate = "activityDate"
    case addedDate = "addedDate"
    case bandwidthPriority = "bandwidthPriority"
    case comment = "comment"
    case corruptEver = "corruptEver"
    case creator = "creator"
    case dateCreated = "dateCreated"
    case desiredAvailable = "desiredAvailable"
    case doneDate = "doneDate"
    case downloadDir = "downloadDir"
    case downloadedEver = "downloadedEver"
    case downloadLimit = "downloadLimit"
    case downloadLimited = "downloadLimited"
    case editDate = "editDate"
    case error = "error"
    case errorString = "errorString"
    case eta = "eta"
    case etaIdle = "etaIdle"
    case files = "files"
    case fileStats = "fileStats"
    case hashString = "hashString"
    case haveUnchecked = "haveUnchecked"
    case haveValid = "haveValid"
    case honorsSessionLimits = "honorsSessionLimits"
    case id = "id"
    case isFinished = "isFinished"
    case isPrivate = "isPrivate"
    case isStalled = "isStalled"
    case labels = "labels"
    case leftUntilDone = "leftUntilDone"
    case magnetLink = "magnetLink"
    case manualAnnounceTime = "manualAnnounceTime"
    case maxConnectedPeers = "maxConnectedPeers"
    case metadataPercentComplete = "metadataPercentComplete"
    case name = "name"
    case peerLimit = "peer-limit"
    case peers = "peers"
    case peersConnected = "peersConnected"
    case peersFrom = "peersFrom"
    case peersGettingFromUs = "peersGettingFromUs"
    case peersSendingToUs = "peersSendingToUs"
    case percentDone = "percentDone"
    case pieces = "pieces"
    case pieceCount = "pieceCount"
    case pieceSize = "pieceSize"
    case priorities = "priorities"
    case queuePosition = "queuePosition"
    case rateDownload = "rateDownload"
    case rateUpload = "rateUpload"
    case recheckProgress = "recheckProgress"
    case secondsDownloading = "secondsDownloading"
    case secondsSeeding = "secondsSeeding"
    case seedIdleLimit = "seedIdleLimit"
    case seedIdleMode = "seedIdleMode"
    case seedRatioLimit = "seedRatioLimit"
    case seedRatioMode = "seedRatioMode"
    case sizeWhenDone = "sizeWhenDone"
    case startDate = "startDate"
    case status = "status"
    case trackers = "trackers"
    case trackerStats = "trackerStats"
    case totalSize = "totalSize"
    case torrentFile = "torrentFile"
    case uploadedEver = "uploadedEver"
    case uploadLimit = "uploadLimit"
    case uploadLimited = "uploadLimited"
    case uploadRatio = "uploadRatio"
    case wanted = "wanted"
    case webseeds = "webseeds"
    case webseedsSendingToUs = "webseedsSendingToUs"
}
